### ISSUE TITLE
兄弟，有版权的，建议你抓紧注明转载。

### ISSUE THREAD

**Issue by Zoutao6** [m969130721/webike#1]
兄弟，有版权的，建议你抓紧注明转载。

**Comment by m969130721** [comment]
了解

**Comment by m969130721** [comment]
我自己写的还有版权？？自己告自己？




| |
潘伟明
邮箱：m969130721@163.com
|

签名由 网易邮箱大师 定制

在2018年09月10日 21:37，zoutao 写道：

兄弟，有版权的，建议你抓紧注明转载。
