### ISSUE TITLE
大佬，为啥pom.xml文件maven会报错呀...

### ISSUE THREAD

**Issue by FabbyBlaire** [m969130721/webike#12]

**Comment by ChinaWim** [comment]
报啥错呀，可以加我qq969130721看看呀










在 2021-05-13 10:13:38，"FabbyBlaire" ***@***.***> 写道：

Closed #12.

**Comment by FabbyBlaire** [comment]
我电脑的问题，已经解决了，感谢大佬拯救我的毕设！！

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月14日(周五) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ChinaWim/webike] 大佬，为啥pom.xml文件maven会报错呀... (#12)




 
 
 
 
 
 
 报啥错呀，可以加我qq969130721看看呀
 
 
 
 
 
 
 
 
 
 
 在 2021-05-13 10:13:38，"FabbyBlaire" ***@***.***&gt; 写道：
 
 Closed #12.
